[package]
name = "zer_os"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nasm-rs = "0.3.0"

[profile.dev]
panic = "abort"
lto = true

[profile.release]
panic = "abort"
lto = true

[build]
build = "main.rs"

[package.metadata.cargo-xbuild]
target = "i686-unknown-none-elf.json"

