[tasks.create_bin_dir]
condition = { platforms = ["windows"] }
script = ["mkdir bin"]

[tasks.create_bin_dir_unix]
condition = { platforms = ["linux", "mac"] }
script = ["mkdir -p bin"]

[tasks.bin]
dependencies = ["create_bin_dir", "create_bin_dir_unix"]
command = "nasm"
args = ["-f", "bin", "./src/boot/boot.asm", "-o", "./bin/boot.bin"]

[tasks.clean_windows]
condition = { platforms = ["windows"] }
script = ["rmdir /S /Q bin"]

[tasks.clean_unix]
condition = { platforms = ["linux", "mac"] }
script = ["rm -rf ./bin"]

[tasks.clean]
dependencies = ["clean_windows", "clean_unix"]